[phases.setup]
# toolchain per build (Ubuntu noble) + setuptools
aptPkgs = ['python3-dev', 'build-essential', 'python3-setuptools']

[phases.install]
# 1) crea venv isolata
# 2) usa il python/pip della venv per installare requirements
cmds = [
  'python -m venv /opt/venv',
  '/opt/venv/bin/python -m pip install --upgrade pip',
  '/opt/venv/bin/python -m pip install -r requirements.txt'
]

[start]
# avvia uvicorn usando la venv
cmd = '/opt/venv/bin/uvicorn main:app --host 0.0.0.0 --port $PORT'
